---
- name: Create a new directory in the EFS mount
  command: mkdir -p /efs/grafana
- name: copy database to directory in the EFS mount
  command: cp /var/grafana/grafana.db /efs/grafana
- name: copy file plugins to directory in the EFS mount
  command: cp -R /var/grafana/plugins /efs/grafana
- name: copy file sessions to directory in the EFS mount
  command: cp -R /var/grafana/sessions /efs/grafana
- name: Permission 
  command: chmod 777 –R  /efs/grafana
  
- name: edit change path database in the file configure  
  lineinfile:
        path: /etc/grafana/grafana.ini
        line: data = /efs/grafana
        insertafter: ;data = /var/lib/grafana
- name: edit change path database in the file configure  
  lineinfile:
        path: /etc/grafana/grafana.ini
        line: plugins = /efs/grafana/plugins
        insertafter: ;plugins = /var/lib/grafana/plugins  
 
- replace:
        dest=/etc/init.d/grafana-server
        regexp='DATA_DIR=/var/lib/grafana'
        replace='DATA_DIR=/efs/grafana'
        backup=yes
- replace:
        dest=/etc/init.d/grafana-server
        regexp='PLUGINS_DIR=/var/lib/grafana/plugins'
        replace='PLUGINS_DIR=/efs/grafana/plugins'
        backup=yes         
  notify: 
  - restart grafana-server

- name: Start Grafana Service
  service: name=grafana-server state=started enabled=yes
